# Generated by Django 2.2 on 2020-01-01 20:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20191230_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='expression',
            name='article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Article'),
        ),
        migrations.AddField(
            model_name='expression',
            name='author',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='expression',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Comment'),
        ),
        migrations.AddField(
            model_name='expression',
            name='expression_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.ExpressionType'),
        ),
        migrations.AddField(
            model_name='expressiontype',
            name='name',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='expression',
            unique_together={('author', 'comment', 'article')},
        ),
        migrations.AddConstraint(
            model_name='expression',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('comment__isnull', True), ('article__isnull', False)), models.Q(('comment__isnull', False), ('article__isnull', True)), _connector='OR'), name='check_expression_target'),
        ),
    ]
