# Generated by Django 2.2 on 2020-01-02 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200102_0009'),
    ]

    operations = [
        migrations.AddField(
            model_name='expressiontype',
            name='name',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='expression',
            unique_together={('expressed', 'comment', 'article')},
        ),
    ]
